filetype off
set nocompatible

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-fugitive'
Plugin 'tmux-plugins/vim-tmux-focus-events'
Plugin 'mileszs/ack.vim'
Plugin 'universal-ctags/ctags'
Plugin 'suoto/vim-hdl'
Plugin 'lervag/vim-foam'
Plugin 'ycm-core/YouCompleteMe'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'godlygeek/tabular'
Plugin 'kkoomen/vim-doge'
Plugin 'turbio/bracey.vim'

call vundle#end()
filetype plugin indent on


" global preferences "
colorscheme industry
set nu
set t_Co=256
set mouse=a
set termencoding=utf-8
set clipboard=unnamedplus
set clipboard=unnamed

" Remember info about open buffers on close
set viminfo^=%

" Backup
set undofile
set noswapfile
set nobackup

" Sounds
set noerrorbells
set novisualbell

" search
set smartcase
set ignorecase
set incsearch
set showmatch

" indention
set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" highlighting
syntax on
set relativenumber
set hlsearch

" Folding
set foldenable

set foldmethod=marker

au FileType sh let g:sh_fold_enabled=7

au FileType sh let g:is_bash=1

au FileType sh set foldmethod=syntax

syntax enable

filetype indent on

set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
set laststatus=2

set updatetime=100

set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯЖ;ABCDEFGHIJKLMNOPQRSTUVWXYZ:,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

" Airline
let g:airline_theme='deus'
" enable YCM integration
let g:airline#extensions#ycm#enabled = 1
" set error count prefix
let g:airline#extensions#ycm#error_symbol = 'E:'
" set warning count prefix
let g:airline#extensions#ycm#warning_symbol = 'W:'
