#!/usr/bin/zsh

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ; then
    PATH=$PATH:"$HOME/.local/bin"
fi

if [ -d "/opt/intel/quartus/20.1/quartus/bin" ] ; then
    PATH=$PATH:"/opt/intel/quartus/20.1/quartus/bin"
fi

if [ -d "/opt/intel/quartus/20.1/quartus/sopc_builder/bin" ] ; then
    PATH=$PATH:"/opt/intel/quartus/20.1/quartus/sopc_builder/bin"
fi

if [ -d "/opt/intel/quartus/20.1/modelsim_ase/bin" ] ; then
    PATH=$PATH:"/opt/intel/quartus/20.1/modelsim_ase/bin"
fi

export PATH
